version: '3.8'

services:
  telegram-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-service
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: pg_online_course
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_courses
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
