version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg_online_course
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_courses
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_course_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app/cmd
    command: ["./main"]

volumes:
  pgdata:
